version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-api-app:production
    container_name: express-api-container-prod
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
