version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-api-app:simple
    container_name: express-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
